[package]
name = "pyttfwrap"
version = "0.1.1"
edition = "2018"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
owned_ttf_parser = "0.12.0"
pyo3 = { version = "0.20.2", features = ["extension-module"] }
ttf_word_wrap = "0.5.0"
unicode-segmentation = "1.10.1"
